### ISSUE TITLE
pipeline relation extract  多subject的情况

### ISSUE THREAD

**Issue by cronousbaby** [percent4/ccks_triple_extract#1]
比如这个样本
李强，男，汉族，出生于1971年12月，北京市人，韩梅，女，回族，出生于1988年3月，河北省人。
 {'OBJ': ['汉族', '1971年12月', '北京市','回族','1988年3月','河北省'], 'SUBJ': ['李强','韩梅']} 三元组： [['李强', '民族', '汉族'], ['李强', '出生地', '北京市'], ['李强', '毕业院校', '北京市委党校'], ['李强', '出生日期', '1971年12月']，['韩梅', '民族', '回族'], ['韩梅', '出生地', '河北省'], ['韩梅', '出生日期', '1988年3月']]
当前流水线关系分类能够识别这种情况的三元组吗，会不会造成错误传播的情况 比如把李强的民族设备成了回族的情况

**Comment by percent4** [comment]
当前的模型是可以识别出这样的情况。但是我估计当前的数据不支持，因为大多数数据都是一个主体。如果训练数据存在这样的情况，那么模型应该是支持多subject的识别的，请知悉。
